name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:8
        ports:
          - 27017:27017

    strategy:
      matrix:
        language: [node, python]

    steps:
    - uses: actions/checkout@v3       # Updated to version 3

    # Node.js Service Setup
    - name: Set up Node.js
      if: matrix.language == 'node'
      uses: actions/setup-node@v3      # Updated to version 3
      with:
        node-version: '20'             # Ensure we're using the latest Node.js version

    - name: Install Dependencies (Node.js)
      if: matrix.language == 'node'
      run: |
        npm install
        npm test

    # Python Service Setup
    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies (Python)
      if: matrix.language == 'python'
      run: |
        pip install -r requirements.txt
        pytest
